# Start Up

Run the cells below. They will open a browser window through selenium. (check your open windows if you don't notice it. It will be a firefox page with an orange url bar.)

Log into your ESPN account and navigate to the draft.

Make sure to keep everything in a single tab. Do not open links as new windows, do not open links as new tabs. This should be the default behavior if you just click on things normally (but no promises - this is hacked together at best...)

### Updating the probabilities

The default score/pick probability info is for 10 team, standard (non-ppr) scoring.

You can update the probabilities with different parameters ```yahoowizard.create_prob_pickle(teams, outputname, mapping_path, scoring, outputpath)``` where teams is the number of teams in your league, and scoring is one of these four entries:
 - 'standard'
 - 'ppr'
 - 'half-ppr'
 - '2qb

The other parameters deal with file mappings.
 
Follow this link to see the source data [Fantasy Football Calculator](https://fantasyfootballcalculator.com/scenario-calculator)

### Updating/Changing the Projections

You can call ```yahoowizard.process_projections(projection_path, idmap_path, output_path)```
to update or change the projections. ```projection_path``` is the direction to the projection files. I use [fantasyfootballanalytics.net](https://www.fantasyfootballanalytics.net)

You can use any source of projections as long as you can map them to the ESPN IDs. 

Required columns:
 - 'position'
 - 'player'
 - 'points'
 - 'adp'
 
This needs more development, specifically:
 - mapping tables to cross-reference all the different sources to some sort of master ID
 - It would also be useful to map the player IDs to the different providers.
 - making the column naming more flexible 
 
 
 # Current Use.
 tells you how to use it... tbd

In [22]:
import pandas as pd 
import numpy as np
import yahoowizard as yw

# projections

In [23]:
proj_name = 'yahoo_players.pkl'
prob_name = 'pick_prob_NEW_10_standard.pkl'

yw.process_projections('ffa_customrankings2020-0.csv',
                       'espn_ffa_map.csv',
                       proj_name)

# yw.update_probabilities(10,
#                         'standard',
#                         prob_name,
#                         'probmap.csv')

projections = pd.read_pickle(proj_name)

probabilities = pd.read_pickle(prob_name)

In [24]:
league_id = 10103683
your_first_pick = 6

In [25]:
draft = yw.YahooDraft(league_id, your_first_pick)

In [26]:
draft.league_id

'10103683'

In [27]:
draft.first_pick

6

In [28]:
draft.current_pick

1

In [29]:
draft.num_teams

14

In [32]:
oc = yw.tell_me_what_to_do(projections,probabilities,draft)
cols = ['player','team','position','points','adp','oc_raw_0','oc_adj_0','oc_adj_1']
print('\nRoster Needs')
print(draft.pos_needs.loc[['QB','RB','WR','TE','D/ST','K']])
print('\n')
oc[cols].sort_values('oc_adj_1',ascending=False).head(10)

TypeError: bad operand type for unary ~: 'float'

In [ ]:
projections = yw.blacklist_player('Leonard Fournette','JAC',projections)
# projections = yw.unblacklist_player('Leonard Fournette','JAC',projections)

In [17]:
players = draft.update(projections)

In [18]:
def next_picks(pick_order, mypick, thispick):
    next_pick = pick_order.index(mypick,thispick) + 1
    next_pick2 = pick_order.index(mypick,next_pick) + 1
    return next_pick, next_pick2

def adj_probs(players,probs, next_pick, next_pick2):
    players['oc_adj'] = players['need_adj']*1 + ~players['need_adj']*players['oc_mult']
    players['espn_id'] = players['espn_id'].astype(str)
    probs['espnid'] = probs['espnid'].astype(str)
    for i, pick in enumerate([next_pick,next_pick2]):
        pmask = probs['pick'] == pick
        df = players.merge(probs[pmask], how='left', left_on='espn_id', right_on='espnid')
        df['%'] = df['%'].fillna(1)
        df['%'] = np.where(df['picked'] | df['blacklist'], 0, df['%'])
        df['probpicked'] = 1 - df['%']
        df = df.groupby('position').apply(expected_max)
        palt = df.groupby('position')['emax'].sum()
        df['opp'] = df['position'].map(palt)
        players[f'oc_raw_{i}'] = (df['points'] - df['opp']) * df['probpicked'] * ~df['picked'] * ~df['blacklist']
        players[f'oc_adj_{i}'] = players[f'oc_raw_{i}'] * players['oc_adj']
        players[f'pb_{i}'] = df['probpicked']
    return players.copy()

In [19]:
np1, np2 = next_picks(draft.pick_order, draft.my_team, draft.current_pick)

In [20]:
np1, np2

(6, 23)

In [103]:
projections[projections['position']=='DST'][['player','team','espn_id']].sort_values('team')

          player team espn_id
85        Ravens  BAL     bal
102        Bills  BUF     buf
125        Bears  CHI     chi
1031      Browns  CLE     cle
1036     Cowboys  DAL     dal
1028     Broncos  DEN     den
1034     Packers   GB      gb
1035      Texans  HOU     hou
1013       Colts  IND     ind
1033     Jaguars  JAC     jax
1014      Chiefs   KC      kc
1039    Chargers  LAC     lac
996         Rams  LAR     lar
1001     Vikings  MIN     min
998     Patriots   NE      ne
1002      Saints   NO      no
1029        Jets  NYJ     nyj
1027      Eagles  PHI     phi
208     Steelers  PIT     pit
1021    Seahawks  SEA     sea
76         49ers   SF      sf
1009  Buccaneers   TB      tb
1022      Titans  TEN     ten
1032    Redskins  WAS     wsh

In [44]:
nfl = pd.read_json('nfl.json')

In [101]:
nfl[nfl['position'] == 'DEF'].sort_index()

,position,search_rank,practice_participation,birth_state,search_full_name,injury_status,stats_id,player_id,practice_description,status,...,weight,injury_body_part,first_name,sportradar_id,years_exp,sport,search_first_name,birth_date,team,birth_city
ARI,DEF,NaN,NaN,NaN,NaN,NaN,NaN,ARI,NaN,NaN,...,NaN,NaN,Arizona,NaN,NaN,nfl,NaN,NaN,ARI,NaN
ATL,DEF,NaN,NaN,NaN,NaN,NaN,NaN,ATL,NaN,NaN,...,NaN,NaN,Atlanta,NaN,NaN,nfl,NaN,NaN,ATL,NaN
BAL,DEF,NaN,NaN,NaN,NaN,NaN,NaN,BAL,NaN,NaN,...,NaN,NaN,Baltimore,NaN,NaN,nfl,NaN,NaN,BAL,NaN
BUF,DEF,NaN,NaN,NaN,NaN,NaN,NaN,BUF,NaN,NaN,...,NaN,NaN,Buffalo,NaN,NaN,nfl,NaN,NaN,BUF,NaN
CAR,DEF,NaN,NaN,NaN,NaN,NaN,NaN,CAR,NaN,NaN,...,NaN,NaN,Carolina,NaN,NaN,nfl,NaN,NaN,CAR,NaN
CHI,DEF,NaN,NaN,NaN,NaN,NaN,NaN,CHI,NaN,NaN,...,NaN,NaN,Chicago,NaN,NaN,nfl,NaN,NaN,CHI,NaN
CIN,DEF,NaN,NaN,NaN,NaN,NaN,NaN,CIN,NaN,NaN,...,NaN,NaN,Cincinnati,NaN,NaN,nfl,NaN,NaN,CIN,NaN
CLE,DEF,NaN,NaN,NaN,NaN,NaN,NaN,CLE,NaN,NaN,...,NaN,NaN,Cleveland,NaN,NaN,nfl,NaN,NaN,CLE,NaN
DAL,DEF,NaN,NaN,NaN,NaN,NaN,NaN,DAL,NaN,NaN,...,NaN,NaN,Dallas,NaN,NaN,nfl,NaN,NaN,DAL,NaN
DEN,DEF,NaN,NaN,NaN,NaN,NaN,NaN,DEN,NaN,NaN,...,NaN,NaN,Denver,NaN,NaN,nfl,NaN,NaN,DEN,NaN
DET,DEF,NaN,NaN,NaN,NaN,NaN,NaN,DET,NaN,NaN,...,NaN,NaN,Detroit,NaN,NaN,nfl,NaN,NaN,DET,NaN
GB,DEF,NaN,NaN,NaN,NaN,NaN,NaN,GB,NaN,NaN,...,NaN,NaN,Green Bay,NaN,NaN,nfl,NaN,NaN,GB,NaN
HOU,DEF,NaN,NaN,NaN,NaN,NaN,NaN,HOU,NaN,NaN,...,NaN,NaN,Houston,NaN,NaN,nfl,NaN,NaN,HOU,NaN
IND,DEF,NaN,NaN,NaN,NaN,NaN,NaN,IND,NaN,NaN,...,NaN,NaN,Indianapolis,NaN,NaN,nfl,NaN,NaN,IND,NaN
JAX,DEF,NaN,NaN,NaN,NaN,NaN,NaN,JAX,NaN,NaN,...,NaN,NaN,Jacksonville,NaN,NaN,nfl,NaN,NaN,JAX,NaN
KC,DEF,NaN,NaN,NaN,NaN,NaN,NaN,KC,NaN,NaN,...,NaN,NaN,Kansas City,NaN,NaN,nfl,NaN,NaN,KC,NaN
LAC,DEF,NaN,NaN,NaN,NaN,NaN,NaN,LAC,NaN,NaN,...,NaN,NaN,Los Angeles,NaN,NaN,nfl,NaN,NaN,LAC,NaN
LAR,DEF,NaN,NaN,NaN,NaN,NaN,NaN,LAR,NaN,NaN,...,NaN,NaN,Los Angeles,NaN,NaN,nfl,NaN,NaN,LAR,NaN
LV,DEF,NaN,NaN,NaN,NaN,NaN,NaN,LV,NaN,NaN,...,NaN,NaN,Las Vegas,NaN,NaN,nfl,NaN,NaN,LV,NaN
MIA,DEF,NaN,NaN,NaN,NaN,NaN,NaN,MIA,NaN,NaN,...,NaN,NaN,Miami,NaN,NaN,nfl,NaN,NaN,MIA,NaN
MIN,DEF,NaN,NaN,NaN,NaN,NaN,NaN,MIN,NaN,NaN,...,NaN,NaN,Minnesota,NaN,NaN,nfl,NaN,NaN,MIN,NaN
NE,DEF,NaN,NaN,NaN,NaN,NaN,NaN,NE,NaN,NaN,...,NaN,NaN,New England,NaN,NaN,nfl,NaN,NaN,NE,NaN
NO,DEF,NaN,NaN,NaN,NaN,NaN,NaN,NO,NaN,NaN,...,NaN,NaN,New Orleans,NaN,NaN,nfl,NaN,NaN,NO,NaN
NYG,DEF,NaN,NaN,NaN,NaN,NaN,NaN,NYG,NaN,NaN,...,NaN,NaN,New York,NaN,NaN,nfl,NaN,NaN,NYG,NaN
NYJ,DEF,NaN,NaN,NaN,NaN,NaN,NaN,NYJ,NaN,NaN,...,NaN,NaN,New York,NaN,NaN,nfl,NaN,NaN,NYJ,NaN
PHI,DEF,NaN,NaN,NaN,NaN,NaN,NaN,PHI,NaN,NaN,...,NaN,NaN,Philadelphia,NaN,NaN,nfl,NaN,NaN,PHI,NaN
PIT,DEF,NaN,NaN,NaN,NaN,NaN,NaN,PIT,NaN,NaN,...,NaN,NaN,Pittsburgh,NaN,NaN,nfl,NaN,NaN,PIT,NaN
SEA,DEF,NaN,NaN,NaN,NaN,NaN,NaN,SEA,NaN,NaN,...,NaN,NaN,Seattle,NaN,NaN,nfl,NaN,NaN,SEA,NaN
SF,DEF,NaN,NaN,NaN,NaN,NaN,NaN,SF,NaN,NaN,...,NaN,NaN,San Francisco,NaN,NaN,nfl,NaN,NaN,SF,NaN
TB,DEF,NaN,NaN,NaN,NaN,NaN,NaN,TB,NaN,NaN,...,NaN,NaN,Tampa Bay,NaN,NaN,nfl,NaN,NaN,TB,NaN
TEN,DEF,NaN,NaN,NaN,NaN,NaN,NaN,TEN,NaN,NaN,...,NaN,NaN,Tennessee,NaN,NaN,nfl,NaN,NaN,TEN,NaN
WAS,DEF,NaN,NaN,NaN,NaN,NaN,NaN,WAS,NaN,NaN,...,NaN,NaN,Washington,NaN,NaN,nfl,NaN,NaN,WAS,NaN

In [110]:
def_map = pd.read_clipboard()

In [111]:
def_map

   index espn_id  yahoo_id
0    ARI     ari    100022
1    ATL     atl    100001
2    BAL     bal    100033
3    BUF     buf    100002
4    CAR     car    100029
5    CHI     chi    100003
6    CIN     cin    100004
7    CLE     cle    100005
8    DAL     dal    100006
9    DEN     den    100007
10   DET     det    100008
11    GB      gb    100009
12   HOU     hou    100034
13   IND     ind    100011
14   JAX     jax    100030
15    KC      kc    100012
16   LAC     lac    100024
17   LAR     lar    100014
18    LV      lv    100013
19   MIA     mia    100015
20   MIN     min    100016
21    NE      ne    100017
22    NO      no    100018
23   NYG     nyg    100019
24   NYJ     nyj    100020
25   PHI     phi    100021
26   PIT     pit    100023
27   SEA     sea    100026
28    SF      sf    100025
29    TB      tb    100027
30   TEN     ten    100010
31   WAS     was    100028

In [112]:
def_map = def_map.astype(str).set_index('index')

In [119]:
nfl['mapping_val'] = nfl.index

In [ ]:
nfl['mapping_val']

In [121]:
nfl['yahoo_id_def'] = nfl['mapping_val'].map(def_map['yahoo_id'])

In [124]:
nfl['yahoo_id'] = nfl['yahoo_id'].fillna(nfl['yahoo_id_def'])

In [125]:
nfl = nfl.drop(columns=['yahoo_id_def'])

In [126]:
nfl.to

,position,search_rank,practice_participation,birth_state,search_full_name,injury_status,stats_id,player_id,practice_description,status,...,injury_body_part,first_name,sportradar_id,years_exp,sport,search_first_name,birth_date,team,birth_city,mapping_val
2103,OT,9999999,None,None,codybooth,None,None,2103,None,Inactive,...,None,Cody,4cd4976e-e230-4935-ad3f-c12876a41350,1,nfl,cody,1991-04-22,None,None,2103
6250,DT,9999999,None,None,eurndrausbryant,NA,None,6250,None,Inactive,...,None,Eurndraus,9ff46edb-988f-4c8a-ad56-0502808ca1a6,0,nfl,eurndraus,None,None,None,6250
4116,OT,9999999,None,None,antoniogarcia,None,None,4116,None,Inactive,...,None,Antonio,a2b6e1f9-1f06-45e3-b6e9-79ec8490e5ef,3,nfl,antonio,1993-12-10,None,None,4116
6177,NT,1594,None,None,khalensaunders,None,None,6177,None,Active,...,None,Khalen,757c55e1-2f3a-41d2-a211-16bf577a1586,1,nfl,khalen,1996-08-09,KC,None,6177
5870,QB,107,None,None,danieljones,None,879981,5870,None,Active,...,None,Daniel,0042266b-cb28-4012-bfd2-06650badad97,1,nfl,daniel,1997-05-27,NYG,None,5870
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3684,WR,9999999,None,None,derekkeaton,None,None,3684,None,Inactive,...,None,Derek,,0,nfl,derek,1994-04-10,None,None,3684
3252,CB,1021,None,None,kendallfuller,None,None,3252,None,Active,...,None,Kendall,81ba31db-e21a-4944-8d0f-4e12cb83e3c4,4,nfl,kendall,1995-02-13,WAS,None,3252
7459,OLB,9999999,None,None,rashodberry,None,None,7459,None,Active,...,None,Rashod,17a17a1a-787d-46b3-94c0-8d4e1928c492,0,nfl,rashod,1996-10-14,NE,None,7459
5135,WR,9999999,None,None,saeedblacknall,None,835780,5135,None,Active,...,None,Saeed,6427f177-527b-435a-bcd1-27cf913f7e24,2,nfl,saeed,1996-03-17,PIT,None,5135
3086,None,9999999,None,None,tomcoughlin,None,None,3086,None,Inactive,...,None,Tom,,0,nfl,tom,None,None,None,3086

In [52]:
draft.update(projections)

,playerId,player,team,position,age,exp,bye,points,lower,upper,...,blacklist,oc_mult,player_id,stats_id,yahoo_id,rotowire_id,rotoworld_id,fantasy_data_id,sportradar_id,need_adj
0,2557997,Christian McCaffrey,CAR,RB,24.0,3.0,NaN,288.366982,264.047189,302.226315,...,False,0.5,4034,830517,30121,11690,12198,18877,f96db0af-5e25-42d1-a07a-49b4e065b364,True
1,2560968,Saquon Barkley,NYG,RB,23.0,2.0,NaN,268.684802,244.354993,296.986985,...,False,0.5,4866,883302,30972,12507,13048,19766,9811b753-347c-467a-b3cb-85937e71e2b9,True
2,2555224,Ezekiel Elliott,DAL,RB,25.0,4.0,NaN,256.402365,238.539195,278.376832,...,False,0.5,3164,728338,29238,10736,11265,17923,bef8b2b4-78bd-4a4d-bb5d-6b55ada9ef6a,True
3,2556075,Derrick Henry,TEN,RB,26.0,4.0,NaN,238.018517,217.315797,246.640252,...,False,0.5,3198,732145,29279,10819,11238,17959,87c481c7-7414-43cc-82df-19ca0c2ae22e,True
4,2557991,Dalvin Cook,MIN,RB,25.0,3.0,NaN,236.090508,217.707601,247.833873,...,False,0.5,4029,824080,30154,11700,12138,18872,8960d61e-433b-41ea-a7ad-4e76be87b582,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1049,2560967,Kalen Ballage,NYJ,RB,NaN,2.0,NaN,3.400000,3.400000,3.400000,...,False,0.5,4994,820568,31100,12786,13216,19824,c6728282-0648-4926-a07c-be64f3ff5e0d,True
1050,2558008,Mitchell Trubisky,CHI,QB,26.0,3.0,NaN,139.232788,82.696006,182.197451,...,False,0.3,3976,728169,30115,11709,12135,18811,7a1b8f1a-9024-4897-86b0-01c63e00305e,True
1051,2564499,Tua Tagovailoa,MIA,QB,50.0,0.0,NaN,89.183127,31.485395,125.272132,...,False,0.3,6768,nan,32675,14465,14839,21677,26ad9c27-de38-495e-913c-6fb2428e76d3,True
1052,2555261,Jacoby Brissett,IND,QB,28.0,4.0,NaN,24.340159,-1.461997,46.612120,...,False,0.3,3257,607047,29325,10919,11341,18018,ad2258ab-67f0-41c2-bcf3-f3ba145187dc,True
1053,2552033,Jameis Winston,NO,QB,26.0,5.0,NaN,18.937285,-2.046796,43.927509,...,False,0.3,2306,691536,28389,10037,9376,16762,fb3b36fc-b985-4807-8199-d038d7e62a93,True

In [56]:
draft.update(projections)

,playerId,player,team,position,age,exp,bye,points,lower,upper,...,blacklist,oc_mult,player_id,stats_id,yahoo_id,rotowire_id,rotoworld_id,fantasy_data_id,sportradar_id,need_adj
0,2557997,Christian McCaffrey,CAR,RB,24.0,3.0,NaN,288.366982,264.047189,302.226315,...,False,0.5,4034,830517,30121,11690,12198,18877,f96db0af-5e25-42d1-a07a-49b4e065b364,True
1,2560968,Saquon Barkley,NYG,RB,23.0,2.0,NaN,268.684802,244.354993,296.986985,...,False,0.5,4866,883302,30972,12507,13048,19766,9811b753-347c-467a-b3cb-85937e71e2b9,True
2,2555224,Ezekiel Elliott,DAL,RB,25.0,4.0,NaN,256.402365,238.539195,278.376832,...,False,0.5,3164,728338,29238,10736,11265,17923,bef8b2b4-78bd-4a4d-bb5d-6b55ada9ef6a,True
3,2556075,Derrick Henry,TEN,RB,26.0,4.0,NaN,238.018517,217.315797,246.640252,...,False,0.5,3198,732145,29279,10819,11238,17959,87c481c7-7414-43cc-82df-19ca0c2ae22e,True
4,2557991,Dalvin Cook,MIN,RB,25.0,3.0,NaN,236.090508,217.707601,247.833873,...,False,0.5,4029,824080,30154,11700,12138,18872,8960d61e-433b-41ea-a7ad-4e76be87b582,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1049,2560967,Kalen Ballage,NYJ,RB,NaN,2.0,NaN,3.400000,3.400000,3.400000,...,False,0.5,4994,820568,31100,12786,13216,19824,c6728282-0648-4926-a07c-be64f3ff5e0d,True
1050,2558008,Mitchell Trubisky,CHI,QB,26.0,3.0,NaN,139.232788,82.696006,182.197451,...,False,0.3,3976,728169,30115,11709,12135,18811,7a1b8f1a-9024-4897-86b0-01c63e00305e,True
1051,2564499,Tua Tagovailoa,MIA,QB,50.0,0.0,NaN,89.183127,31.485395,125.272132,...,False,0.3,6768,nan,32675,14465,14839,21677,26ad9c27-de38-495e-913c-6fb2428e76d3,True
1052,2555261,Jacoby Brissett,IND,QB,28.0,4.0,NaN,24.340159,-1.461997,46.612120,...,False,0.3,3257,607047,29325,10919,11341,18018,ad2258ab-67f0-41c2-bcf3-f3ba145187dc,True
1053,2552033,Jameis Winston,NO,QB,26.0,5.0,NaN,18.937285,-2.046796,43.927509,...,False,0.3,2306,691536,28389,10037,9376,16762,fb3b36fc-b985-4807-8199-d038d7e62a93,True

In [57]:
draft.picked_players

27277      1
30121      1
30123      1
32705      1
32722      1
25785      2
28403      2
29344      2
30218      2
30972      2
26699      3
27540      3
29238      3
30362      3
31010      3
27589      4
28457      4
30180      4
30199      4
32711      4
26664      5
29279      5
29369      5
30197      5
30996      5
26650      6
27535      6
32702      6
100021     6
100025     6
29384      7
30161      7
30209      7
31031      7
31833      7
26658      8
29281      8
30295      8
30994      8
26671      9
30175      9
31856      9
31885      9
26686     10
28398     10
30154     10
30182     10
Name: team, dtype: int64

In [53]:
draft.picked_players

27277      1
30121      1
30123      1
28403      2
30218      2
30972      2
27540      3
29238      3
30362      3
27589      4
30180      4
32711      4
29279      5
29369      5
30197      5
30996      5
26650      6
27535      6
32702      6
100021     6
30161      7
30209      7
31031      7
31833      7
26658      8
29281      8
30295      8
30994      8
26671      9
30175      9
31856      9
31885      9
26686     10
28398     10
30154     10
30182     10
Name: team, dtype: int64

In [54]:
from yahoo_oauth import OAuth2
oauth = OAuth2(None, None, from_file='oauth.json')
if not oauth.token_is_valid():
    oauth.refresh_access_token()

[2020-09-04 20:32:38,479 DEBUG] [yahoo_oauth.oauth.__init__] Checking
[2020-09-04 20:32:38,492 DEBUG] [yahoo_oauth.oauth.token_is_valid] ELAPSED TIME : 1279.1252927780151
[2020-09-04 20:32:38,493 DEBUG] [yahoo_oauth.oauth.token_is_valid] TOKEN IS STILL VALID
[2020-09-04 20:32:38,496 DEBUG] [yahoo_oauth.oauth.token_is_valid] ELAPSED TIME : 1279.1292827129364
[2020-09-04 20:32:38,496 DEBUG] [yahoo_oauth.oauth.token_is_valid] TOKEN IS STILL VALID

In [80]:
r = oauth.session.get('https://fantasysports.yahooapis.com/fantasy/v2/league/nfl.l.1022820/players;player_keys=nfl.p.100032')

In [81]:
print(r.text)

<?xml version="1.0" encoding="UTF-8"?>
<error xml:lang="en-us" yahoo:uri="http://fantasysports.yahooapis.com/fantasy/v2/league/nfl.l.1022820/players;player_keys=nfl.p.100032" xmlns:yahoo="http://www.yahooapis.com/v1/base.rng" xmlns="http://www.yahooapis.com/v1/base.rng">
 <description>Player key 399.p.100032 does not exist.</description>
 <detail/>
</error>

In [85]:
draft.scrape_draft()

In [87]:
draft.picked_players

27277      1
27591      1
29269      1
30121      1
30123      1
          ..
28534     10
30154     10
30182     10
31008     10
100002    10
Name: team, Length: 95, dtype: int64

In [89]:
import xml.etree.ElementTree as ET 
import re

In [90]:
players = {}
teams = draft.num_teams
for i in range(1,teams+1):
    _url = f"{draft.league_url}/teams;team_keys=nfl.l.{draft.league_id}.t.{i}/players"
    _r = oauth.session.get(_url)
    xmlstring = _r.text
    xmlstring = re.sub(' xmlns="[^"]+"', '', xmlstring, count=1)
    root = ET.fromstring(xmlstring)
    for player in root.iter('player_id'):
        players[player.text] = i

In [91]:
players

{'24057': 1,
 '27277': 1,
 '27591': 1,
 '29269': 1,
 '30121': 1,
 '30123': 1,
 '30346': 1,
 '31021': 1,
 '32705': 1,
 '32722': 1,
 '100017': 1,
 '24791': 2,
 '25785': 2,
 '25876': 2,
 '28403': 2,
 '29344': 2,
 '29754': 2,
 '30218': 2,
 '30972': 2,
 '32756': 2,
 '100007': 2,
 '24788': 3,
 '26699': 3,
 '27540': 3,
 '29238': 3,
 '29255': 3,
 '29274': 3,
 '30362': 3,
 '30995': 3,
 '31010': 3,
 '31838': 3,
 '5479': 4,
 '25881': 4,
 '27589': 4,
 '28457': 4,
 '30136': 4,
 '30180': 4,
 '30199': 4,
 '31017': 4,
 '32711': 4,
 '100018': 4,
 '26664': 5,
 '29279': 5,
 '29369': 5,
 '30197': 5,
 '30232': 5,
 '30784': 5,
 '30996': 5,
 '31001': 5,
 '31905': 5,
 '31906': 5,
 '5228': 6,
 '26534': 6,
 '26650': 6,
 '27535': 6,
 '31012': 6,
 '31898': 6,
 '32702': 6,
 '100021': 6,
 '100025': 6,
 '100034': 6,
 '28592': 7,
 '29384': 7,
 '30161': 7,
 '30209': 7,
 '30971': 7,
 '31031': 7,
 '31833': 7,
 '31888': 7,
 '32003': 7,
 '32736': 7,
 '7200': 8,
 '8565': 8,
 '26658': 8,
 '29236': 8,
 '29281': 8,
 '30295': 8,
 '30552': 8,
 '30994': 8,
 '31896': 8,
 '100016': 8,
 '24017': 9,
 '26671': 9,
 '29288': 9,
 '30125': 9,
 '30175': 9,
 '30256': 9,
 '31856': 9,
 '31885': 9,
 '32687': 9,
 '100012': 9,
 '7520': 10,
 '9265': 10,
 '26686': 10,
 '27619': 10,
 '28398': 10,
 '28534': 10,
 '30154': 10,
 '30182': 10,
 '31008': 10,
 '100002': 10,
 '6770': 11,
 '9496': 11,
 '24815': 11,
 '25802': 11,
 '26804': 11,
 '27548': 11,
 '27581': 11,
 '28474': 11,
 '29307': 11,
 '31051': 11,
 '9353': 12,
 '27658': 12,
 '28654': 12,
 '30337': 12,
 '31002': 12,
 '31005': 12,
 '31857': 12,
 '31883': 12,
 '32671': 12,
 '100003': 12,
 '8780': 13,
 '24793': 13,
 '29235': 13,
 '29399': 13,
 '30266': 13,
 '31056': 13,
 '31379': 13,
 '31908': 13,
 '32725': 13,
 '100023': 13,
 '28392': 14,
 '28402': 14,
 '28461': 14,
 '28493': 14,
 '30117': 14,
 '30259': 14,
 '30423': 14,
 '30977': 14,
 '31977': 14,
 '100033': 14}

In [46]:
nfl = nfl.T

In [50]:
nfl[nfl['position'] == 'DEF'][['player_id','espn_id','yahoo_id']]

    player_id espn_id yahoo_id
WAS       WAS     NaN      NaN
ARI       ARI     NaN      NaN
ATL       ATL     NaN      NaN
TEN       TEN     NaN      NaN
LAR       LAR     NaN      NaN
PIT       PIT     NaN      NaN
NE         NE     NaN      NaN
CLE       CLE     NaN      NaN
SEA       SEA     NaN      NaN
HOU       HOU     NaN      NaN
LV         LV     NaN      NaN
LAC       LAC     NaN      NaN
BAL       BAL     NaN      NaN
PHI       PHI     NaN      NaN
JAX       JAX     NaN      NaN
GB         GB     NaN      NaN
NYG       NYG     NaN      NaN
IND       IND     NaN      NaN
NYJ       NYJ     NaN      NaN
CIN       CIN     NaN      NaN
MIA       MIA     NaN      NaN
CAR       CAR     NaN      NaN
NO         NO     NaN      NaN
SF         SF     NaN      NaN
DAL       DAL     NaN      NaN
DEN       DEN     NaN      NaN
TB         TB     NaN      NaN
CHI       CHI     NaN      NaN
KC         KC     NaN      NaN
BUF       BUF     NaN      NaN
MIN       MIN     NaN      NaN
DET       DET     NaN      NaN

In [40]:
players['need_adj'].unique()

array([True, nan], dtype=object)

In [36]:
players['need_adj']*1 + (~players['need_adj'])

TypeError: bad operand type for unary ~: 'float'